export const GET_MANAGE_PAYMENT_REQUEST = "GET_MANAGE_PAYMENT_REQUEST";
export const GET_MANAGE_PAYMENT_SUCCESS = "GET_MANAGE_PAYMENT_SUCCESS";
export const GET_MANAGE_PAYMENT_FAIL = "GET_MANAGE_PAYMENT_FAIL";