export const GET_SIP_SIP_PROFILE_REQUEST = "GET_SIP_SIP_PROFILE_REQUEST";
export const GET_SIP_SIP_PROFILE_SUCCESS = "GET_SIP_SIP_PROFILE_SUCCESS";
export const GET_SIP_SIP_PROFILE_FAIL = "GET_SIP_SIP_PROFILE_FAIL";

export const CREATE_SIP_SIP_PROFILE_REQUEST = "CREATE_SIP_SIP_PROFILE_REQUEST";
export const CREATE_SIP_SIP_PROFILE_SUCCESS = "CREATE_SIP_SIP_PROFILE_SUCCESS";
export const CREATE_SIP_SIP_PROFILE_FAIL = "CREATE_SIP_SIP_PROFILE_FAIL";

export const UPDATE_SIP_SIP_PROFILE_REQUEST = "UPDATE_SIP_SIP_PROFILE_REQUEST";
export const UPDATE_SIP_SIP_PROFILE_SUCCESS = "UPDATE_SIP_SIP_PROFILE_SUCCESS";
export const UPDATE_SIP_SIP_PROFILE_FAIL = "UPDATE_SIP_SIP_PROFILE_FAIL";

export const DELETE_SIP_SIP_PROFILE_REQUEST = "DELETE_SIP_SIP_PROFILE_REQUEST";
export const DELETE_SIP_SIP_PROFILE_SUCCESS = "DELETE_SIP_SIP_PROFILE_SUCCESS";
export const DELETE_SIP_SIP_PROFILE_FAIL = "DELETE_SIP_SIP_PROFILE_FAIL";