export const GET_ADMIN_ROLES_REQUEST = "GET_ADMIN_ROLES_REQUEST";
export const GET_ADMIN_ROLES_SUCCESS = "GET_ADMIN_ROLES_SUCCESS";
export const GET_ADMIN_ROLES_FAIL = "GET_ADMIN_ROLES_FAIL";

export const CREATE_ADMIN_ROLES_REQUEST = "CREATE_ADMIN_ROLES_REQUEST";
export const CREATE_ADMIN_ROLES_SUCCESS = "CREATE_ADMIN_ROLES_SUCCESS";
export const CREATE_ADMIN_ROLES_FAIL = "CREATE_ADMIN_ROLES_FAIL";

export const UPDATE_ADMIN_ROLES_REQUEST = "UPDATE_ADMIN_ROLES_REQUEST";
export const UPDATE_ADMIN_ROLES_SUCCESS = "UPDATE_ADMIN_ROLES_SUCCESS";
export const UPDATE_ADMIN_ROLES_FAIL = "UPDATE_ADMIN_ROLES_FAIL";