export const GET_ADMIN_LOCAL_REQUEST = "GET_ADMIN_LOCAL_REQUEST";
export const GET_ADMIN_LOCAL_SUCCESS = "GET_ADMIN_LOCAL_SUCCESS";
export const GET_ADMIN_LOCAL_FAIL = "GET_ADMIN_LOCAL_FAIL";

export const CREATE_ADMIN_LOCAL_REQUEST = "CREATE_ADMIN_LOCAL_REQUEST";
export const CREATE_ADMIN_LOCAL_SUCCESS = "CREATE_ADMIN_LOCAL_SUCCESS";
export const CREATE_ADMIN_LOCAL_FAIL = "CREATE_ADMIN_LOCAL_FAIL";

export const UPDATE_ADMIN_LOCAL_REQUEST = "UPDATE_ADMIN_LOCAL_REQUEST";
export const UPDATE_ADMIN_LOCAL_SUCCESS = "UPDATE_ADMIN_LOCAL_SUCCESS";
export const UPDATE_ADMIN_LOCAL_FAIL = "UPDATE_ADMIN_LOCAL_FAIL";

export const DELETE_ADMIN_LOCAL_REQUEST = "DELETE_ADMIN_LOCAL_REQUEST";
export const DELETE_ADMIN_LOCAL_SUCCESS = "DELETE_ADMIN_LOCAL_SUCCESS";
export const DELETE_ADMIN_LOCAL_FAIL = "DELETE_ADMIN_LOCAL_FAIL";

export const GET_ADMIN_BILLING_LOCAL_REQUEST = "GET_ADMIN_BILLING_LOCAL_REQUEST";
export const GET_ADMIN_BILLING_LOCAL_SUCCESS = "GET_ADMIN_BILLING_LOCAL_SUCCESS";
export const GET_ADMIN_BILLING_LOCAL_FAIL = "GET_ADMIN_BILLING_LOCAL_FAIL";

export const GET_ADMIN_TOTAL_LOCAL_REQUEST = "GET_ADMIN_TOTAL_LOCAL_REQUEST";
export const GET_ADMIN_TOTAL_LOCAL_SUCCESS = "GET_ADMIN_TOTAL_LOCAL_SUCCESS";
export const GET_ADMIN_TOTAL_LOCAL_FAIL = "GET_ADMIN_TOTAL_LOCAL_FAIL";