export const GET_ADMIN_PAYMENT_REQUEST = "GET_ADMIN_PAYMENT_REQUEST";
export const GET_ADMIN_PAYMENT_SUCCESS = "GET_ADMIN_PAYMENT_SUCCESS";
export const GET_ADMIN_PAYMENT_FAIL = "GET_ADMIN_PAYMENT_FAIL";