export const GET_ADMIN_SIP_PROFILE_REQUEST = "GET_ADMIN_SIP_PROFILE_REQUEST";
export const GET_ADMIN_SIP_PROFILE_SUCCESS = "GET_ADMIN_SIP_PROFILE_SUCCESS";
export const GET_ADMIN_SIP_PROFILE_FAIL = "GET_ADMIN_SIP_PROFILE_FAIL";

export const CREATE_ADMIN_SIP_PROFILE_REQUEST = "CREATE_ADMIN_SIP_PROFILE_REQUEST";
export const CREATE_ADMIN_SIP_PROFILE_SUCCESS = "CREATE_ADMIN_SIP_PROFILE_SUCCESS";
export const CREATE_ADMIN_SIP_PROFILE_FAIL = "CREATE_ADMIN_SIP_PROFILE_FAIL";

export const UPDATE_ADMIN_SIP_PROFILE_REQUEST = "UPDATE_ADMIN_SIP_PROFILE_REQUEST";
export const UPDATE_ADMIN_SIP_PROFILE_SUCCESS = "UPDATE_ADMIN_SIP_PROFILE_SUCCESS";
export const UPDATE_ADMIN_SIP_PROFILE_FAIL = "UPDATE_ADMIN_SIP_PROFILE_FAIL";

export const DELETE_ADMIN_SIP_PROFILE_REQUEST = "DELETE_ADMIN_SIP_PROFILE_REQUEST";
export const DELETE_ADMIN_SIP_PROFILE_SUCCESS = "DELETE_ADMIN_SIP_PROFILE_SUCCESS";
export const DELETE_ADMIN_SIP_PROFILE_FAIL = "DELETE_ADMIN_SIP_PROFILE_FAIL";